paths:
  /projects/{projectId}:
    patch:
      summary: Update project fields
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                  format: uuid
                  example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                nameProject:
                  type: string
                  example: string
                startData:
                  type: string
                  format: date
                  example: string
                endData:
                  type: string
                  format: date
                  example: string
                radius:
                  type: number
                  example: 0
                projectEmployees:
                  type: array
                  items:
                    type: object
                    properties:
                      employeeId:
                        type: string
                        format: uuid
                        example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                projectHeadSites:
                  type: array
                  items:
                    type: object
                    properties:
                      headSiteId:
                        type: string
                        format: uuid
                        example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                      startDate:
                        type: string
                        format: date
                        example: string
                      endDate:
                        type: string
                        format: date
                        example: string
                longitude:
                  type: number
                  example: 0
                latitude:
                  type: number
                  example: 0
      responses:
        '200':
          description: Successfully updated the project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projects'
        '404':
          description: Project not found
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    Projects:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
        nameProject:
          type: string
        startData:
          type: string
          format: date
        endData:
          type: string
          format: date
        radius:
          type: number
        projectEmployees:
          type: array
          items:
            type: object
            properties:
              employeeId:
                type: string
                format: uuid
        projectHeadSites:
          type: array
          items:
            type: object
            properties:
              headSiteId:
                type: string
                format: uuid
              startDate:
                type: string
                format: date
              endDate:
                type: string
                format: date
        longitude:
          type: number
        latitude:
          type: number
